### ISSUE TITLE
Config Bug?

### ISSUE THREAD

**Issue by TempusVulpi** [Azami7/Ollivanders2#90] opened 2017-08-26 00:03 UTC
Setting certain Config options, such as Divination or Booklearning has no effect, Booklearning just stays enabled no matter what and Divination never seems to work

**Comment by Azami7** [comment] 2017-09-17 21:07
Divination - yea, not sure it works at all.  We have had issues making it work too and are not sure if it never worked on the original Ollivanders plugin or needs to be fixed to work with current MC versions

Book Leanring - I'll take a look.  We have it enabled on our server but we did not used to and never had a problem with it.  I'll turn it off on our test server and see if I can repro your issue.

**Comment by Azami7** [comment] 2017-09-18 00:59
I tried setting bookLearning to false on my local server and didn't have a problem.  If you've confirmed your config file says:

bookLearning: false

Let me know what, exact, behavior you are seeing and whether there is anything in the logs.  When book learning is on, saying a spell you do not know and then left-clicking causes nothing to happen.  If you are seeing the particle effect when you say a spell and left-click, but the spell isn't working, then something else is going on.  Unfortunately, we have not added debug sections to this part of the code since we have not changed it from the original but I can add some and give you a new .jar file so we might get some more insight in to what is happening on your server.

**Comment by TempusVulpi** [comment] 2017-09-18 21:45
I used the original Ollivanders for many years and i can confirm Divination worked, i'm not much of a coder so i can only assume something about the newer MC versions broke it, 

As for bookLearning, i apologize, i actually stated the opposite of what i meant, I have bookLearning enabled and the problem is that when it's enabled you can still use any spell as if you'd read a book containing it. there's no console output, no errors, nothing in the logs to imply something has gone wrong, yet it acts as if it's not even there.

**Comment by Azami7** [comment] 2018-01-15 06:55
@TempusVulpi can you confirm that book learning is now working with 2.2.6 - https://s3-us-west-2.amazonaws.com/pottercraft/Ollivanders2-2.2.6.jar

You will want to use the /ollivanders2 books commands. See https://github.com/Azami7/Ollivanders2/wiki/Books

**Comment by TempusVulpi** [comment] 2018-01-15 15:57
I tried running it on my server, can confirm book learning now works.

**Comment by Azami7** [comment] 2018-02-11 03:54
Fix released with 2.2.6

**Closed by Azami7** 2018-02-11 03:54 UTC
